<?php

/**
 * Created by PhpStorm.
 * User: jhonnymatracas
 * Date: 1/01/17
 * Time: 14:38
 */
class ErrorForm extends Session
{

    public static function addNegative($value)
    {
        parent::add('feedback_negative', $value); // TODO: Change the autogenerated stub
    }

    public static function addPositive($value)
    {
        parent::add('feedback_positive', $value); // TODO: Change the autogenerated stub
    }
}