<?php

/**
 * Created by PhpStorm.
 * User: jhonnymatracas
 * Date: 1/01/17
 * Time: 14:38
 */
class ErrorForm extends Session
{

    public static function addNegative($value)
    {
        parent::add('feedback_negative', $value); // TODO: Change the autogenerated stub
    }

    public static function addPositive($value)
    {
        parent::add('feedback_positive', $value); // TODO: Change the autogenerated stub

    }

    public static function addFeedback_Form($a,$b)
    {
        parent::addOne('fb_form',$a,$b); // TODO: Change the autogenerated stub

    }

    public static function status($a)
    {
        $fb = parent::get('fb_form');

        if (isset($fb[$a])) {

            return $fb[$a];

        }

    }
}