<?php

/**
 * Created by PhpStorm.
 * User: jhonnymatracas
 * Date: 1/01/17
 * Time: 14:38
 */
class Feedback extends Session
{

    public static function addNegative($value)
    {
        parent::add('feedback_negative', $value); // TODO: Change the autogenerated stub
    }

    public static function addPositive($value)
    {
        parent::add('feedback_positive', $value); // TODO: Change the autogenerated stub

    }

    public static function addFeedback_Form($a,$b)
    {
        parent::addOne('fb_form',$a,$b); // TODO: Change the autogenerated stub

    }

    public static function addInputMessage($a,$b)
    {
        parent::add($a,$b); // TODO: Change the autogenerated stub

    }

    public static function getInputMessage($a)
    {
        if (! is_null(Session::get($a)) && count(Session::get($a)) > 0) {
         $message = '<div><ul class="feedback_input_form">';

            foreach(Session::get($a) as $error){
                $message .= '<li>'. $error .'</li>';
            }
            $message .= '</ul></div>';

            return $message;
        }else
            return '';
}

    public static function status($a)
    {
        $fb = parent::get('fb_form');

        if (isset($fb[$a])) {

            return $fb[$a];

        }

    }

    public static function cssFeedback($a,$b = null)
    {
        if ($b == null) {
            if (is_null(self::status($a))) {
                return '';
            } else {
                if (!self::status($a)) {
                    return 'has-error';
                } else {
                    return 'has-success';
                }
            }
        }else{
            if (is_null(self::status($a)) || is_null(self::status($b))) {
                return '';
            } else {
                if (!self::status($a) || !self::status($b)) {
                    return 'has-error';
                } else {
                    return 'has-success';
                }
            }
        }
    }

    public static function iconFeedback($a,$b=null)
    {
            switch (self::cssFeedback($a,$b)) {
                case '':
                    return '';
                    break;
                case 'has-error':
                    return '<span class="glyphicon glyphicon-remove form-control-feedback"></span>';
                    break;
                case 'has-success':
                    return '<span class="glyphicon glyphicon-ok form-control-feedback"></span>';
                    break;

            }

    }
}